#############################################################################
# Makefile for building: least_squares
# Generated by qmake (2.01a) (Qt 4.7.2) on: Sun Jun 3 18:38:26 2012
# Project:  least_squares.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile least_squares.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -fopenmp -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -fopenmp -lQtOpenGL -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		main_window.cpp \
		glwidget.cpp \
		approximator.cpp \
		ilu.cpp \
		bcgstab.cpp \
		array_op.cpp \
		polynom.cpp moc_main_window.cpp \
		moc_glwidget.cpp \
		moc_approximator.cpp
OBJECTS       = main.o \
		main_window.o \
		glwidget.o \
		approximator.o \
		ilu.o \
		bcgstab.o \
		array_op.o \
		polynom.o \
		moc_main_window.o \
		moc_glwidget.o \
		moc_approximator.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		least_squares.pro
QMAKE_TARGET  = least_squares
DESTDIR       = 
TARGET        = least_squares

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_main_window.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: least_squares.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile least_squares.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile least_squares.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/least_squares1.0.0 || $(MKDIR) .tmp/least_squares1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/least_squares1.0.0/ && $(COPY_FILE) --parents main_window.h glwidget.h approximator.h precond.h iter_alg.h array_op.h polynom.h .tmp/least_squares1.0.0/ && $(COPY_FILE) --parents main.cpp main_window.cpp glwidget.cpp approximator.cpp ilu.cpp bcgstab.cpp array_op.cpp polynom.cpp .tmp/least_squares1.0.0/ && $(COPY_FILE) --parents main_window.ui .tmp/least_squares1.0.0/ && (cd `dirname .tmp/least_squares1.0.0` && $(TAR) least_squares1.0.0.tar least_squares1.0.0 && $(COMPRESS) least_squares1.0.0.tar) && $(MOVE) `dirname .tmp/least_squares1.0.0`/least_squares1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/least_squares1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_main_window.cpp moc_glwidget.cpp moc_approximator.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_main_window.cpp moc_glwidget.cpp moc_approximator.cpp
moc_main_window.cpp: glwidget.h \
		approximator.h \
		polynom.h \
		main_window.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) main_window.h -o moc_main_window.cpp

moc_glwidget.cpp: approximator.h \
		polynom.h \
		glwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) glwidget.h -o moc_glwidget.cpp

moc_approximator.cpp: polynom.h \
		approximator.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) approximator.h -o moc_approximator.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_main_window.h
compiler_uic_clean:
	-$(DEL_FILE) ui_main_window.h
ui_main_window.h: main_window.ui
	/usr/bin/uic-qt4 main_window.ui -o ui_main_window.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp main_window.h \
		glwidget.h \
		approximator.h \
		polynom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

main_window.o: main_window.cpp main_window.h \
		glwidget.h \
		approximator.h \
		polynom.h \
		ui_main_window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_window.o main_window.cpp

glwidget.o: glwidget.cpp glwidget.h \
		approximator.h \
		polynom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidget.o glwidget.cpp

approximator.o: approximator.cpp approximator.h \
		polynom.h \
		precond.h \
		iter_alg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o approximator.o approximator.cpp

ilu.o: ilu.cpp precond.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ilu.o ilu.cpp

bcgstab.o: bcgstab.cpp array_op.h \
		precond.h \
		iter_alg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bcgstab.o bcgstab.cpp

array_op.o: array_op.cpp array_op.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o array_op.o array_op.cpp

polynom.o: polynom.cpp polynom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o polynom.o polynom.cpp

moc_main_window.o: moc_main_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main_window.o moc_main_window.cpp

moc_glwidget.o: moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidget.o moc_glwidget.cpp

moc_approximator.o: moc_approximator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_approximator.o moc_approximator.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

